name: Proxcord
version: 1.0.0
main: com.proxcord.free.ProxcordFreePlugin
api-version: '1.21'
author: DynamicKing
description: A free proximity voice chat integration for DiscordSRV.
depend: [DiscordSRV]

commands:
  voice:
    description: Open the Proxcord voice settings menu.
    usage: /voice
    permission: proxcord.voice

permissions:
  proxcord.voice:
    description: Allows players to open the voice GUI.
    default: true